# Swarm of 6 robots

In [150]:
import pandas as pd
import numpy as np
import random

# Intial Map

In [160]:
x = np.ones((10, 10))
x[:, :] = 0
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Random position of 6 robots

In [161]:
res = []
for j in range(6): 
    res.append(random.randint(0, 99))
res

[66, 10, 43, 50, 38, 93]

In [162]:
robotsX = []
robotsY = []
for i in range(6):
    robotsX.append(res[i]//10)
    robotsY.append(res[i]%10)
print(robotsX)
robotsY

[6, 1, 4, 5, 3, 9]


[6, 0, 3, 0, 8, 3]

In [163]:
lastPosX = robotsX.copy()
lastPosY = robotsY.copy()

## Robots in those random positions: 1 stands for first robot, 2 for second robot and so on

In [164]:
for i in range(6):
    x[robotsX[i]][robotsY[i]] = i+1
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.]])

In [165]:
InitialMap = x.copy()

## Simple swarm algorithm

In [166]:
def swar():
    for i in range(6):
        if (((lastPosX[i]+1) < 10) and (x[lastPosX[i]+1][lastPosY[i]] == 0.0)):
            robotsX.append(lastPosX[i]+1)
            robotsY.append(lastPosY[i])
        
        elif (((lastPosX[i]-1) > -1) and (x[lastPosX[i]-1][lastPosY[i]] == 0.0)):
            robotsX.append(lastPosX[i]-1)
            robotsY.append(lastPosY[i])
        
        elif (((lastPosY[i]+1) < 10) and (x[lastPosX[i]][lastPosY[i]+1] == 0.0)):
            robotsY.append(lastPosY[i]+1)
            robotsX.append(lastPosX[i])
        
        elif (((lastPosY[i]-1) > -1) and (x[lastPosX[i]][lastPosY[i]-1] == 0.0)):
            robotsY.append(lastPosY[i]-1)
            robotsX.append(lastPosX[i])
        
        else:
            robotsX.append(lastPosX[i])
            robotsY.append(lastPosY[i])

    #print(robotsX)
    #print(robotsY)
    for i in range(len(robotsX)):
        x[robotsX[i]][robotsY[i]] = (i%6)+1
    print(x)
    for i in range(6):
        lastPosX[i] = robotsX[(len(robotsX)-1+i)-5]
        lastPosY[i] = robotsY[(len(robotsY)-1+i)-5]
    #print(lastPosX)
    #print(lastPosY)

## Running the algorithm for 20 steps - Trajectory of the robot in each step

In [167]:
for i in range(20):
    print("Map in", i ,"th run" )
    swar()

Map in 0 th run
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 5. 0.]
 [4. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]]
Map in 1 th run
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 5. 0.]
 [4. 0. 0. 3. 0. 0. 0. 0. 5. 0.]
 [4. 0. 0. 3. 0. 0. 1. 0. 0. 0.]
 [4. 0. 0. 6. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]]
Map in 2 th run
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [2. 0. 0. 3. 0. 0. 0. 0. 5. 0.]
 [4. 0. 0. 3. 0. 0. 0. 0. 5. 0.]
 [4. 0. 0. 3. 3. 0. 1. 0. 5. 0.]
 [4. 0. 0. 6. 6. 0. 1. 0. 0. 0.]
 [4. 0. 0. 6. 0. 0. 1. 0. 

In [168]:
FinalMap = x.copy()

## Initial Map where the robots are positioned

In [170]:
InitialMap

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.]])

## Final Map where the robots have mapped

In [169]:
FinalMap

array([[0., 0., 0., 0., 3., 3., 3., 1., 1., 5.],
       [2., 0., 0., 0., 3., 3., 3., 1., 1., 5.],
       [2., 0., 0., 0., 3., 3., 3., 1., 1., 5.],
       [2., 0., 0., 0., 3., 6., 6., 1., 5., 5.],
       [2., 2., 0., 3., 3., 6., 6., 1., 5., 5.],
       [4., 2., 0., 3., 3., 6., 6., 1., 5., 5.],
       [4., 2., 0., 3., 3., 6., 1., 1., 5., 5.],
       [4., 4., 4., 6., 6., 6., 1., 1., 5., 5.],
       [4., 4., 4., 6., 6., 6., 1., 1., 5., 5.],
       [4., 4., 4., 6., 6., 6., 1., 1., 5., 5.]])

The number 1 stands for the regions where first robot mapped, 2 stands for second robot and so on. The let out are marked as 0, which would also be traveresed for more runs.